hmcts/service-auth-provider-app

settings.gradle
=> Configure reform artifactory repo to download totp jar

api/src/functionalTest/java/FunctionalTest.java
Make functional tests compile
```
[ ] Yes
[x] No
```
=> Make functional tests compile

api/src/main/java/uk/gov/hmcts/auth/provider/service/api/auth/AuthController.java, api/src/main/java/uk/gov/hmcts/auth/provider/service/api/model/SignIn.java, api/src/main/java/uk/gov/hmcts/auth/provider/service/api/model/TokenDetails.java, api/src/test/java/uk/gov/hmcts/auth/provider/service/api/componenttests/dsl/ServiceAuthProviderTestDsl.java, token-generator/src/main/java/uk/gov/hmcts/auth/provider/service/token/HttpComponentsBasedServiceTokenGenerator.java, token-generator/src/test/java/uk/gov/hmcts/auth/provider/service/token/HttpComponentsBasedServiceTokenGeneratorTest.java
=> Update request body json

api/src/main/resources/application.yml, api/src/test/resources/application.yml, build.gradle, lib/AI-Agent.xml
=> Enable AppInsights logging

build.gradle
Minor clean up.
```
[ ] Yes
[x] No
```
=> Remove unnecessary logging dependencies

infrastructure/variables.tf
=> set default value for testing_support

build.gradle
Missing core hmcts component for logging, _accidentally_ removed with #10 
```
[ ] Yes
[x] No
```
=> Add logging component

Jenkinsfile_tactical
Publish docker images again so that we can use the cnp version of s2s -.-
```
[ ] Yes
[ ] No
```
=> Publish docker images

README.md
Adding readme to test permissions
```
[ ] Yes
[ ] No
```
=> Add empty README

build.gradle
- Added dependency check plugin config.
- No suppressions added apart from the one already added.
- Successful build link https://build.platform.hmcts.net/job/HMCTS/job/service-auth-provider-app/view/change-requests/job/PR-19/
```
[ ] Yes
[x ] No
```
=> Added dependency check plugin configuration

api/src/main/java/uk/gov/hmcts/auth/provider/service/api/microservice/MicroserviceRepository.java
At the moment app crashes with NullPointerException
=> Handle lack of configured services

api/build.gradle, api/src/main/java/uk/gov/hmcts/auth/provider/service/api/ServiceAuthProviderApplication.java, api/src/main/java/uk/gov/hmcts/auth/provider/service/api/auth/AuthService.java, api/src/main/java/uk/gov/hmcts/auth/provider/service/api/auth/totp/TotpAuthenticator.java, api/src/test/java/uk/gov/hmcts/auth/provider/service/api/auth/AuthServiceTest.java, api/src/test/java/uk/gov/hmcts/auth/provider/service/api/componenttests/LeaseComponentTest.java
In preparation for removing the following modules:
- token-generator
- token-generator-spring
=> Move otp helper to api module

api/src/main/java/uk/gov/hmcts/auth/provider/service/api/auth/AuthService.java, api/src/main/java/uk/gov/hmcts/auth/provider/service/api/error/ErrorDto.java, api/src/main/java/uk/gov/hmcts/auth/provider/service/api/microservice/Microservice.java, api/src/test/java/uk/gov/hmcts/auth/provider/service/api/componenttests/DetailsComponentTest.java, api/src/test/java/uk/gov/hmcts/auth/provider/service/api/componenttests/LeaseComponentTest.java, api/src/test/java/uk/gov/hmcts/auth/provider/service/api/microservice/MicroserviceRepositoryTest.java
Sonar reports on all the unused (generated) code, for example:
Refactored to use simple, immutable value objects.
=> Don't use lombok for models

Jenkinsfile_CNP, Jenkinsfile_parameterized, api/build.gradle, api/src/functionalTest/java/uk/gov/hmcts/auth/provider/service/api/SignInTest.java, api/src/functionalTest/resources/application.conf, infrastructure/main.tf, infrastructure/output.tf, infrastructure/variables.tf
also required terraform/jenkinsfile changes (separate commits)
=> Add functional test for signing in

.travis.yml, README.md
https://tools.hmcts.net/jira/browse/RPE-397
Add .travis.yml file as a step to integrate with Travis CI. Also, add a Travis badge to README.
```
[ ] Yes
[x] No
```
=> Add Travis file and badge

README.md
https://tools.hmcts.net/jira/browse/RPE-397
Add quality tool badges to README
```
[ ] Yes
[x] No
```
=> Add quality tool badges to README

build.gradle
Checked jenkins report and this change locally, looks like single change solves the dependency check step
```
[ ] Yes
[x] No
```
=> Solve spring boot vulnerabilities

infrastructure/variables.tf
Remove default product name from terraform - Jenkins will take it from Jenkinsfile
```
[ ] Yes
[x] No
```
=> Remove default product name from terraform

README.md, build.gradle, src/main/java/uk/gov/hmcts/auth/provider/service/api/auth/AuthController.java, src/main/java/uk/gov/hmcts/auth/provider/service/api/auth/AuthIntegrationTestSupportController.java, src/main/java/uk/gov/hmcts/auth/provider/service/api/config/SwaggerConfiguration.java, src/main/java/uk/gov/hmcts/auth/provider/service/api/model/SignIn.java, src/main/java/uk/gov/hmcts/auth/provider/service/api/model/SignInWithoutOtp.java
Travis config to publish swagger spec is already on the repo.
=> Add swagger

infrastructure/main.tf
Added entries for `ccdAdmin` client ID.
None.
Vault entries for `ccdAdmin` client ID.
```
[ ] Yes
[x] No
```
=> Add ccdAdmin microservice

infrastructure/main.tf
Correction to Terraform reference; indentation tidying.
None.
Correction to Terraform reference, replacing `contino` with `hmcts`. Also removed extra space in indentation.
```
[ ] Yes
[x] No
```
=> Use open-sourced moj-module-webapp from hmcts organisation

src/test/java/uk/gov/hmcts/auth/provider/service/api/componenttests/dsl/ServiceAuthProviderTestDsl.java
=> Remove unused code

infrastructure/aat.tfvars, infrastructure/main.tf, infrastructure/prod.tfvars, infrastructure/variables.tf
https://tools.hmcts.net/confluence/display/CNP/Preview+Environment#PreviewEnvironment-Reducecapacity
=> Set nodes capacity for azure

infrastructure/main.tf
still waiting on the secret to be added
=> Adding COH-COR to S2S

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RPE-556
Added  key to s2s to run bulk scan functional tests.
```
[ ] Yes
[ x] No
```
=> [PREVIEW]Add bulk scan test key to s2s

infrastructure/main.tf
These changes relate to https://tools.hmcts.net/jira/browse/BAR-395
add bar-api to s2s auth service to be able to authenticate and upload payments to pay-hub
```
[ ] Yes
[ x] No
```
=> Registering bar-api to s2s auth

src/main/java/uk/gov/hmcts/auth/provider/service/api/microservice/MicroserviceRepository.java, src/test/java/uk/gov/hmcts/auth/provider/service/api/microservice/MicroserviceRepositoryTest.java
So that it's easier to find given service.
=> Sort services in info endpoint

infrastructure/main.tf
Change Vault name to include the actual product. Currently, it's just `rpe-{env}`.
```
[ ] Yes
[x] No
```
=> [PREVIEW] Change Vault name to include the actual product

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RPE-614
Use the group that all devs are in to ease on-boarding of services
```
[ ] Yes
[ ] No
```
=> RPE-614 Use group ID that all devs are in

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/PAY-1310
Add API-Gateway as a new service to S2S
```
[ ] Yes
[ x] No
```
=> [PREVIEW] PAY-1310 - added config for new service (API-GW)

README.md
https://tools.hmcts.net/jira/browse/RPE-614
Extend README with info about reading secret from S2S value (in the infrastructure code of client services).
```
[ ] Yes
[x] No
```
=> Extend README with info about reading secret from S2S value

Dockerfile, Jenkinsfile_CNP
We need that S2S generates a docker images that gets stored on Azure Container Registry so other apps using it can docker compose it.
=> Generate docker image

.github/PULL_REQUEST_TEMPLATE.md, bin/check-all-vaults-for-s2s-secret
Adds a script for checking s2s secrets are in place, example output:
```
$ ./bin/check-all-vaults-for-s2s-secret cmc
INFO: Found secret cmc in environment sandbox
INFO: Found secret cmc in environment saat
INFO: Found secret cmc in environment sprod
INFO: Found secret cmc in environment demo
INFO: Found secret cmc in environment aat
INFO: Found secret cmc in environment prod
```
=> Add script for checking if a secret is in all vaults

infrastructure/main.tf
=> Add Civil Enforcement to S2S

infrastructure/main.tf
None
Secret for FPL case service
```
./bin/check-all-vaults-for-s2s-secret fpl-case-service
INFO: Found secret fpl-case-service in environment sandbox
INFO: Found secret fpl-case-service in environment saat
INFO: Found secret fpl-case-service in environment sprod
INFO: Found secret fpl-case-service in environment demo
INFO: Found secret fpl-case-service in environment aat
INFO: Found secret fpl-case-service in environment prod
```
```
[ ] Yes
[x] No
```
=> Add secret for FPL case service

bin/check-all-vaults-for-s2s-secret, bin/set-secret-in-all-vaults, infrastructure/hmctsdemo.tfvars
https://tools.hmcts.net/jira/browse/RPE-845
Adds hmcts demo config
=> RPE-845 Add hmcts demo config

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/SSCS-4504
INFO: Found secret sscs-bulkscan in environment sandbox
INFO: Found secret sscs-bulkscan in environment saat
INFO: Found secret sscs-bulkscan in environment sprod
INFO: Found secret sscs-bulkscan in environment demo
INFO: Found secret sscs-bulkscan in environment hmctsdemo
INFO: Found secret sscs-bulkscan in environment aat
INFO: Found secret sscs-bulkscan in environment prod
```
[ ] Yes
[x] No
```
=> Add sscs-bulkscan to main.tf

infrastructure/aat.tfvars
Needed to simplify ccd chart importer in aat
=> Enable testing support in AAT

DockerHubfile
Dunno why it broke, this fixes it...
=> Fix s2s image

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/FR-611
added new microservice key finrem-ccd-data-migrator to get s2s token.
/bin/check-all-vaults-for-s2s-secret finrem-ccd-data-migrator
ERROR: Didn't find secret finrem-ccd-data-migrator in environment sandbox
ERROR: Didn't find secret finrem-ccd-data-migrator in environment saat
INFO: Found secret finrem-ccd-data-migrator in environment sprod
INFO: Found secret finrem-ccd-data-migrator in environment demo
INFO: Found secret finrem-ccd-data-migrator in environment hmctsdemo
INFO: …
=> FR_611: register finrem-ccd-data-migration-service for s2s token

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDM-3763
Add ccd definition designer service
$ ./bin/check-all-vaults-for-s2s-secret microservicekey-ccd-definition-designer
INFO: Found secret microservicekey-ccd-definition-designer in environment sandbox
INFO: Found secret microservicekey-ccd-definition-designer in environment saat
INFO: Found secret microservicekey-ccd-definition-designer in environment sprod
INFO: Found secret microservicekey-ccd-definition-designer in environment demo
INFO: Found secret microservicekey-ccd-definition-designer in environment hmctsdemo
INFO: Found secret microservicekey-ccd-definition-designer in …
=> RDM-3763 Add ccd definition designer service

build.gradle
fixing owasp failure by upgrading to spring boot 2.1.2
=> fixing owasp failure

infrastructure/main.tf
N/A
added new microservice key EM_STITCHING_API to get s2s token.
```
[ ] Yes
[x] No
```
=> Add stitching API

infrastructure/main.tf
N/A
Added a new secret (for em-ccd-orchestrator).
INFO: Found secret em-ccd-orchestrator in environment sandbox
INFO: Found secret em-ccd-orchestrator in environment saat
INFO: Found secret em-ccd-orchestrator in environment sprod
INFO: Found secret em-ccd-orchestrator in environment demo
INFO: Found secret em-ccd-orchestrator in environment hmctsdemo
INFO: Found secret em-ccd-orchestrator in environment aat
INFO: Found secret em-ccd-orchestrator in environment prod
```
[ ] Yes
[x] No
```
=> add em-ccd-orchestrator

infrastructure/main.tf
Adding s2s token for CCPAY-BUBBLE.
./check-all-vaults-for-s2s-secret ccpay-bubble
INFO: Found secret ccpay-bubble in environment sandbox
INFO: Found secret ccpay-bubble in environment saat
INFO: Found secret ccpay-bubble in environment sprod
INFO: Found secret ccpay-bubble in environment demo
INFO: Found secret ccpay-bubble in environment hmctsdemo
INFO: Found secret ccpay-bubble in environment aat
INFO: Found secret ccpay-bubble in environment prod
```
[ ] Yes
[x] No
```
=> Added ccpay bubble to s2s

infrastructure/main.tf
N/A
Rename key to be shorter
```
INFO: Found secret dg-template-management in environment sandbox
INFO: Found secret dg-template-management in environment saat
INFO: Found secret dg-template-management in environment sprod
INFO: Found secret dg-template-management in environment demo
INFO: Found secret dg-template-management in environment hmctsdemo
INFO: Found secret dg-template-management in environment aat
INFO: Found secret dg-template-management in environment prod
```
```
[ ] Yes
[x] No
```
=> rename template management api key

charts/rpe-service-auth-provider/requirements.yaml
=> Use latest chart-java

charts/rpe-service-auth-provider/Chart.yaml
bump chart version so changes from #129 get published
```
[ ] Yes
[x] No
```
=> bump chart version

build.gradle, dependency-check-suppressions.xml
Bump springframework version 
To fix security vulnerabilities check
```
[ ] Yes
[ x] No
```
=> bump spring version

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/requirements.yaml, charts/rpe-service-auth-provider/values.aat.template.yaml, charts/rpe-service-auth-provider/values.preview.template.yaml, charts/rpe-service-auth-provider/values.yaml
https://tools.hmcts.net/jira/browse/RPE-914
Refactoring preview configurations
```
[ ] Yes
[x] No
```
=> Refactoring preview configurations

README.md
Fixing read me with latest file path
```
[ ] Yes
[x] No
```
=> Fixing read me with latest file path

charts/rpe-service-auth-provider/values.yaml, infrastructure/main.tf, src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/ROC-5263
Adding secret for PAPI claim submission service.
Not sure we need saat, sprod, sandbox anymore? 🤔 
```
./bin/check-all-vaults-for-s2s-secret cmc-claim-external-api         
ERROR: Didn't find secret cmc-claim-external-api in environment sandbox
ERROR: Didn't find secret cmc-claim-external-api in environment saat
ERROR: Didn't find secret cmc-claim-external-api in environment sprod
INFO: Found secret cmc-claim-external-api in environment demo
ERROR: Didn't find secret cmc-claim-external-api in environment hmctsdemo
INFO: Found secret cmc-claim-external-api in environment aat
INFO: Found secret cmc-claim-external-api in environment prod
``` …
=> Add new secret definitions for CMC PAPI service

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/requirements.yaml, charts/rpe-service-auth-provider/values.yaml, src/main/resources/bootstrap.yaml
Added JWTKey from secrets for charts.
```
[ ] Yes
[x ] No
```
=> Add JWTKey from secrets

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/requirements.yaml
https://dev.azure.com/hmcts/Platform%20Engineering/_workitems/edit/109
bump java chart version
```
[ ] Yes
[x] No
```
[AB#109](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/109)
=> bump java chart version AB#109

bin/check-all-vaults-for-s2s-secret, bin/set-secret-in-all-vaults
=> Set keys in perftest and ithc

infrastructure/main.tf
=> Redeploy secrets

infrastructure/main.tf
=> Reload secrets.

charts/rpe-service-auth-provider/values.yaml, infrastructure/main.tf, src/main/resources/bootstrap.yaml
Added ethos-repl-service as microservicekey
Logs:
Javiers-MBP:service-auth-provider-app javiercarretero$ ./bin/check-all-vaults-for-s2s-secret ethos-repl-service
INFO: Found secret ethos-repl-service in environment sandbox
ERROR: Didn't find secret ethos-repl-service in environment saat
INFO: Found secret ethos-repl-service in environment sprod
INFO: Found secret ethos-repl-service in environment demo
ERROR: Didn't find secret ethos-repl-service in environment hmctsdemo
INFO: Found secret ethos-repl-service in …
=> Added ethos-repl-service as microservicekey

README.md, bin/check-all-vaults-for-s2s-secret, bin/set-secret-in-all-vaults, build.gradle, charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/requirements.yaml, charts/rpe-service-auth-provider/values.aat.template.yaml, charts/rpe-service-auth-provider/values.preview.template.yaml, charts/rpe-service-auth-provider/values.yaml, dependency-check-suppressions.xml, infrastructure/main.tf, src/main/resources/bootstrap.yaml
=> Ethos repl service

infrastructure/aat.tfvars, infrastructure/demo.tfvars, infrastructure/ithc.tfvars, infrastructure/perftest.tfvars, infrastructure/preview.tfvars, infrastructure/prod.tfvars, infrastructure/variables.tf
=> Add perftest and ithc envs

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/requirements.yaml
=> Bumping java chart

.github/PULL_REQUEST_TEMPLATE.md, README.md, bin/set-secret-in-all-vaults
-
Remove deleted vaults and generate secret in script
=> Remove deleted vaults and generate secret in script

charts/rpe-service-auth-provider/values.yaml, infrastructure/main.tf, src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/BPS-570
Add a microservice key for the new `bulk-scan-ccd-event-handler-sample-app` application.
```
INFO: Found secret bulk-scan-ccd-sample-app in environment sandbox
ERROR: Didn't find secret bulk-scan-ccd-sample-app in environment saat
ERROR: Didn't find secret bulk-scan-ccd-sample-app in environment sprod
INFO: Found …
```
=> Add a microservice key for bulk-scan-ccd-event-handler-sample-app

infrastructure/main.tf
=> Modify ET Secret

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml
=> Add Employment Tribunals to values

build.gradle
=> Upgrade to owasp 5

charts/rpe-service-auth-provider/values.yaml, infrastructure/main.tf, src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/AM-360
adding access management api services for S2S auth
$ ./set-secret-in-all-vaults am-accessmgmt-api
INFO: Found secret am-accessmgmt-api in environment sandbox
INFO: Found secret am-accessmgmt-api in environment demo
INFO: Found secret am-accessmgmt-api in environment aat
INFO: Found secret am-accessmgmt-api in environment prod
INFO: Found secret am-accessmgmt-api in environment perftest
INFO: Found secret am-accessmgmt-api in environment ithc
```
[ ] Yes
[ x] No
```
=> feat: adding keys for access management apis

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml, infrastructure/main.tf, src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/BPS-683
Add a microservice key for bulk-scan-ccd-event-handler-sample-app tests
```
INFO: Found secret bulk-scan-sample-app-tests in environment sandbox
INFO: Found secret bulk-scan-sample-app-tests in environment demo
INFO: Found secret bulk-scan-sample-app-tests in environment aat
INFO: Found secret bulk-scan-sample-app-tests in environment prod
INFO: Found secret bulk-scan-sample-app-tests in environment perftest
INFO: Found secret bulk-scan-sample-app-tests in environment ithc
```
```
[ ] Yes
[x ] No
```
=> add microservice key for bulk-scan-ccd-event-handler-sample-app tests

charts/rpe-service-auth-provider/values.yaml, infrastructure/main.tf, src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/EUI-524
INFO: Found secret xui-webapp in environment sandbox
INFO: Found secret xui-webapp in environment demo
INFO: Found secret xui-webapp in environment aat
INFO: Found secret xui-webapp in environment prod
INFO: Found secret xui-webapp in environment perftest
INFO: Found secret xui-webapp in environment ithc
=> adding xui-webapp

build.gradle
=> update dependency 

charts/rpe-service-auth-provider/values.yaml, infrastructure/main.tf, src/main/resources/bootstrap.yaml
Adding ctsc_work_allocation microservice to the known services
```
➜  bin git:(master) ./check-all-vaults-for-s2s-secret ctsc-work-allocation 
INFO: Found secret ctsc-work-allocation in environment sandbox
INFO: Found secret ctsc-work-allocation in environment demo
INFO: Found secret ctsc-work-allocation in environment aat
INFO: Found secret ctsc-work-allocation in environment prod
INFO: Found secret ctsc-work-allocation in environment perftest
INFO: Found secret ctsc-work-allocation in environment ithc
```
Adding the values to all required files:
- main.tf
- values.yaml
- bootstrap.yaml
```
[ ] Yes
[X] No
```
=> Adding ctsc-work-allocation microservice

infrastructure/main.tf
=> Remove count change that never made it to master

infrastructure/main.tf
=> Add common tags

build.gradle, src/test/java/uk/gov/hmcts/auth/provider/service/api/auth/JwtHS512ToolTest.java
More reliable build hopefully?
=> Make test more flexible / reliable

web.config
=> fix  app insights version

Jenkinsfile_parameterized
=> fixing parameterized pipeline

infrastructure/main.tf
=> Remove .git suffix for infra-approvals compatibility

Jenkinsfile_CNP
=> Switch off legacy

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml
=> making ingress host dynamic

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml, infrastructure/main.tf, src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/BPS-765
Add a new secret for `bulk-scan-payments-processor` service.
```
INFO: Found secret bulk-scan-payment-processor in environment sandbox
INFO: Found secret bulk-scan-payment-processor in environment demo
INFO: Found secret bulk-scan-payment-processor in environment aat
INFO: Found secret bulk-scan-payment-processor in environment prod
INFO: Found secret bulk-scan-payment-processor in environment perftest
INFO: Found secret bulk-scan-payment-processor in environment ithc
```
```
[ ] Yes
[x] No
```
=> Add microservice key for Bulkscan payment processor

Dockerfile, build.gradle, dependency-check-suppressions.xml, src/main/resources/bootstrap.yaml
=> Fixing bulk scan payment processor'r' and moving to latest appinsights to fix build

dependency-check-suppressions.xml
=> Temporarily suppress OWASP issue

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml, infrastructure/main.tf, src/main/resources/bootstrap.yaml
JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RDCC-854
Adding rd-judicial-api microservice
AGB07392:bin 429962$ ./set-secret-in-all-vaults microservicekey-rd-judicial-api
INFO: Found secret microservicekey-rd-judicial-api in environment sandbox
INFO: Found secret microservicekey-rd-judicial-api in environment demo
INFO: Found secret microservicekey-rd-judicial-api in environment aat
INFO: Found secret microservicekey-rd-judicial-api in environment prod
INFO: Found secret microservicekey-rd-judicial-api in environment perftest
INFO: Found secret microservicekey-rd-judicial-api in environment ithc
**Does this PR …
=>  Adding rd-judicial-api microservice

README.md
=> Adding missing steps for setting up new s2s client

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml, infrastructure/main.tf, src/main/resources/bootstrap.yaml
AMBGB000001:bin 462450$ ./set-secret-in-all-vaults microservicekey-ccd-case-document-am-api
INFO: Found secret microservicekey-ccd-case-document-am-api in environment sandbox
INFO: Found secret microservicekey-ccd-case-document-am-api in environment demo
INFO: Found secret microservicekey-ccd-case-document-am-api in environment aat
INFO: Found secret microservicekey-ccd-case-document-am-api in environment prod
INFO: Found secret microservicekey-ccd-case-document-am-api in environment perftest
INFO: Found secret microservicekey-ccd-case-document-am-api in environment ithc
```
[ ] Yes
[x] No
```
=> Adding ccd case document am api

Jenkinsfile_CNP, charts/rpe-service-auth-provider/values.preview.template.yaml
N/A
Removed deprecated enableDockerBuild in build.gradle
Removed aadIdentityName from values.preview.template.yaml  
```
[ ] Yes
[x] No
```
=> fix: removed unneeded values from pipeline

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml, infrastructure/main.tf, src/main/resources/bootstrap.yaml
N/A
Added 
ERROR: Didn't find secret adoption-backend in environment sandbox
INFO: Found secret adoption-backend in environment demo
INFO: Found secret adoption-backend in environment aat
INFO: Found secret adoption-backend in environment prod
INFO: Found secret adoption-backend in environment perftest
INFO: Found secret adoption-backend in environment ithc
```
[ ] Yes
[ ] No
```
=> Add microservice key for adoption backend

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml, infrastructure/main.tf, src/main/resources/bootstrap.yaml
PAY-3129 : Adding S2S Configuration for Payment App
Adding S2S Configuration for Payment App
---------- ./check-all-vaults-for-s2s-secret payment-app
ERROR: Didn't find secret payment-app in environment sandbox
INFO: Found secret payment-app in environment demo
INFO: Found secret payment-app in environment aat
INFO: Found secret payment-app in environment prod
INFO: Found secret payment-app in environment perftest
INFO: Found secret payment-app in environment ithc
**Does this PR introduce a …
=> PAY-3129 : Adding S2S Configuration for Payment App

infrastructure/demo.tfvars
=> add demo mi

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/requirements.yaml, dependency-check-suppressions.xml
Updated java chart dependency to latest version
```
[ ] Yes
[x] No
```
=> updated java chart dependency

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml, src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/RDM-8445
Update to add PCQ pcq-consolidation-service microservicekeys to service auth.
Had problems running this script...
Davids-MacBook-Pro:service-auth-provider-app davejones$ ./bin/set-secret-in-all-vaults pcq-consolidation-service
./bin/set-secret-in-all-vaults: line 3: realpath: command not found
usage: dirname path
Updated keys manually using java code to generate key. Also I couldn't update for sandbox, output of the check script below.
ERROR: Didn't find secret pcq-consolidation-service in environment sandbox
INFO: Found secret pcq-consolidation-service in environment demo
INFO: Found …
=> RDM 8445 adding pcq s2s keys

bin/check-all-vaults-for-s2s-secret, bin/set-secret-in-all-vaults
This vault doesn't exist anymore
=> Remove sandbox from script

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml, src/main/resources/bootstrap.yaml
Added ecm microservice
Javiers-MBP:bin javiercarretero$ ./check-all-vaults-for-s2s-secret ecm-consumer
ERROR: Didn't find secret ecm-consumer in environment sandbox
INFO: Found secret ecm-consumer in environment demo
INFO: Found secret ecm-consumer in environment aat
INFO: Found secret ecm-consumer in environment prod
INFO: Found secret ecm-consumer in environment perftest
INFO: Found secret ecm-consumer in environment ithc
=> Added ecm microservice

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml, src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/RDM-8493
Registering Manage Case Assignment in S2S
➜  bin git:(aac-manage-case-assignment) ✗ (⎈ perftest-00-aks:default) ./check-all-vaults-for-s2s-secret aac-manage-case-assignment
INFO: Found secret aac-manage-case-assignment in environment demo
INFO: Found secret aac-manage-case-assignment in environment aat
INFO: Found secret aac-manage-case-assignment in environment prod
INFO: Found secret aac-manage-case-assignment in environment perftest
INFO: Found secret aac-manage-case-assignment in environment ithc
➜  bin git:(aac-manage-case-assignment) ✗ (⎈ perftest-00-aks:default) 
```
[ ] Yes
[ x] No
```
=> RDM-8493 - Registering Manage Case Assignment in S2S

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml
[AKS tests for notification service](https://tools.hmcts.net/jira/browse/BPS-1233)
After running script:
```
INFO: Found secret reform-scan-notification-tests in environment demo
INFO: Found secret reform-scan-notification-tests in environment aat
INFO: Found secret reform-scan-notification-tests in environment prod
INFO: Found secret reform-scan-notification-tests in environment perftest
INFO: Found secret reform-scan-notification-tests in environment ithc
```
```
[ ] Yes
[x] No
```
=> Add `reform-scan-notification-tests` secret

Jenkinsfile_CNP
TTL: 2 days
```
[ ] Yes
[x] No
```
=> Remove deprecated flag

src/main/resources/bootstrap.yaml
Forgot to add it while #257 
```
[ ] Yes
[x] No
```
=> Add microservice key to app

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml, src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/AM-738
Onboarding the AM application.
AMBGB000001:service-auth-provider-app 462450$ ./bin/check-all-vaults-for-s2s-secret am-role-assignment-service
INFO: Found secret am-role-assignment-service in environment demo
INFO: Found secret am-role-assignment-service in environment aat
INFO: Found secret am-role-assignment-service in environment prod
INFO: Found secret am-role-assignment-service in environment perftest
INFO: Found secret am-role-assignment-service in environment ithc
```
[ ] Yes
[x] No
```
=> Onboarding AM application.

infrastructure/main.tf
=> Add appinsights key to keyvault

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml, src/main/resources/bootstrap.yaml
=> Add appinsights key to chart

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml, src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/AM-792
AMBGB000001:bin 462450$ ./check-all-vaults-for-s2s-secret am-judicial-booking-service
INFO: Found secret am-judicial-booking-service in environment demo
INFO: Found secret am-judicial-booking-service in environment aat
INFO: Found secret am-judicial-booking-service in environment prod
INFO: Found secret am-judicial-booking-service in environment perftest
INFO: Found secret am-judicial-booking-service in environment ithc
AMBGB000001:bin 462450$ 
```
[ ] Yes
[x] No
```
=> Onboarding AM Judicial Booking application.

.github/renovate.json, charts/rpe-service-auth-provider/Chart.yaml, renovate.json
=> Renovate helm requirements

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml, src/main/resources/bootstrap.yaml
Onboarding AM Organisation Role Mapping application
Onboarding AM Organisation Role Mapping application
AMBGB000045:bin 475495$ ./check-all-vaults-for-s2s-secret am-org-role-mapping-service
INFO: Found secret am-org-role-mapping-service in environment demo
INFO: Found secret am-org-role-mapping-service in environment aat
INFO: Found secret am-org-role-mapping-service in environment prod
INFO: Found secret am-org-role-mapping-service in environment perftest
INFO: Found secret am-org-role-mapping-service in environment ithc
```
[ ] Yes
[x] No
```
=> Onboarding AM Organisation Role Mapping application

Dockerfile, build.gradle, dependency-check-suppressions.xml
AB#948
Accidentally submitted https://github.com/hmcts/service-auth-provider-app/pull/281 from a fork
=> Update to java 11

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml, src/main/resources/bootstrap.yaml
N/A
added UCMC service keys
➜  service-auth-provider-app git:(master) ✗ ./bin/check-all-vaults-for-s2s-secret ucmc-service
INFO: Found secret ucmc-service in environment demo
INFO: Found secret ucmc-service in environment aat
INFO: Found secret ucmc-service in environment prod
INFO: Found secret ucmc-service in environment perftest
INFO: Found secret ucmc-service in environment ithc
```
[ ] Yes
[x] No
```
=> added ucmc-service s2s

infrastructure/aat.tfvars, infrastructure/demo.tfvars, infrastructure/ithc.tfvars, infrastructure/main.tf, infrastructure/perftest.tfvars, infrastructure/prod.tfvars, infrastructure/sandbox.tfvars, infrastructure/variables.tf
=> Remove old MI

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml, src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/CMC-467
```
INFO: Found secret unspec-service in environment demo
INFO: Found secret unspec-service in environment aat
INFO: Found secret unspec-service in environment prod
INFO: Found secret unspec-service in environment perftest
INFO: Found secret unspec-service in environment ithc
```
```
[ ] Yes
[x] No
```
=> Added unspec-service key

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml, src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/CMC-467
Cleanup work after transition to unspec
```
[ ] Yes
[x] No
```
=> Removed ucmc after transition to unspec

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml, src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/AM-938 
Onboarding the RD Caseworker Ref API.
AMBGB000001:bin 462450$ ./check-all-vaults-for-s2s-secret rd-caseworker-ref-api
INFO: Found secret rd-caseworker-ref-api in environment demo
INFO: Found secret rd-caseworker-ref-api in environment aat
INFO: Found secret rd-caseworker-ref-api in environment prod
INFO: Found secret rd-caseworker-ref-api in environment perftest
INFO: Found secret rd-caseworker-ref-api in environment ithc
```
[ ] Yes
[x] No
```
=> Onboarding RD Caseworker Ref API.

README.md
=> Chart update in flux is not needed anymore

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml, src/main/resources/bootstrap.yaml
Oboarding RD Fee Pay Ref Data Load.
AMBGB000001:bin 462450$ ./check-all-vaults-for-s2s-secret rd-fee-pay-ref-data-load
INFO: Found secret rd-fee-pay-ref-data-load in environment demo
INFO: Found secret rd-fee-pay-ref-data-load in environment aat
INFO: Found secret rd-fee-pay-ref-data-load in environment prod
INFO: Found secret rd-fee-pay-ref-data-load in environment perftest
INFO: Found secret rd-fee-pay-ref-data-load in environment ithc
AMBGB000001:bin 462450$ 
```
[ ] Yes
[x] No
```
=> Onboarding RD Fee Pay Ref data load.

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml, src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/RDCC-1769
Renamed rd-fee-pay-ref-data-load to rd-location-data-load
m_794168@AMBGB000096 bin % ./check-all-vaults-for-s2s-secret rd-location-data-load
INFO: Found secret rd-location-data-load in environment demo
INFO: Found secret rd-location-data-load in environment aat
INFO: Found secret rd-location-data-load in environment prod
INFO: Found secret rd-location-data-load in environment perftest
INFO: Found secret rd-location-data-load in environment ithc
```
[ ] Yes
[X] No
```
=> Rename secret name

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml, src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/RWA-97
```
INFO: Found secret wa in environment demo
INFO: Found secret wa in environment aat
INFO: Found secret wa in environment prod
INFO: Found secret wa in environment perftest
INFO: Found secret wa in environment ithc
```
```
[ ] Yes
[X] No
```
=> Setup the s2s secret for WA

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml, src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/RDCC-1769
m_794168@AMBGB000096 bin % ./check-all-vaults-for-s2s-secret rd-location-ref-api
INFO: Found secret rd-location-ref-api in environment demo
INFO: Found secret rd-location-ref-api in environment aat
INFO: Found secret rd-location-ref-api in environment prod
INFO: Found secret rd-location-ref-api in environment perftest
INFO: Found secret rd-location-ref-api in environment ithc
```
[ ] Yes
[X] No
```
=> Add entry for rd-location-ref-api

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml, src/main/resources/bootstrap.yaml
```
INFO: Found secret reform-scan-blob-router in environment demo
INFO: Found secret reform-scan-blob-router in environment aat
INFO: Found secret reform-scan-blob-router in environment prod
INFO: Found secret reform-scan-blob-router in environment perftest
INFO: Found secret reform-scan-blob-router in environment ithc
```
```
[ ] Yes
[x] No
```
=> Add config for blob-router service

bin/set-secret-in-all-vaults
=> updated script comment

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml, src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/RWA-107
```
❯ ./check-all-vaults-for-s2s-secret wa-workflow-api                   
INFO: Found secret wa-workflow-api in environment demo
INFO: Found secret wa-workflow-api in environment aat
INFO: Found secret wa-workflow-api in environment prod
INFO: Found secret wa-workflow-api in environment perftest
INFO: Found secret wa-workflow-api in environment ithc
❯ ./check-all-vaults-for-s2s-secret wa-task-management-api                                                                 
INFO: Found secret wa-task-management-api in environment demo
INFO: Found secret wa-task-management-api in environment aat
INFO: Found secret wa-task-management-api in environment prod
INFO: Found secret wa-task-management-api in environment perftest
INFO: Found secret …
```
=> RWA-107: Setting up work-allocation s2s secrets

Jenkinsfile_CNP, build.gradle, dependency-check-suppressions.xml
=> Upgrade owasp dependencycheck plugin to 6

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml, src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/RWA-49
Setup wa-case-event-handler s2s secrets
```
❯ ./set-secret-in-all-vaults wa-case-event-handler                                                                                                                                                                           
INFO: Found secret wa-case-event-handler in environment demo
INFO: Found secret wa-case-event-handler in environment aat
INFO: Found secret wa-case-event-handler in environment prod
INFO: Found secret wa-case-event-handler in environment perftest
INFO: Found secret wa-case-event-handler in environment ithc
```
```
[ ] Yes
[x ] No
```
=> RWA-49: Setup wa-case-event-handler s2s secrets

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml, src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/RWA-242
Create new s2s secret for camunda pipeline deployment configuration
❯ ./set-secret-in-all-vaults wa-camunda-pipeline-upload                                                                                                                                                                      
INFO: Found secret wa-camunda-pipeline-upload in environment demo
INFO: Found secret wa-camunda-pipeline-upload in environment aat
INFO: Found secret wa-camunda-pipeline-upload in environment prod
INFO: Found secret wa-camunda-pipeline-upload in environment perftest
INFO: Found secret wa-camunda-pipeline-upload in environment ithc
```
[ ] Yes
[x ] No
```
=> Create new s2s secret for camunda pipeline deployment configuration

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml, src/main/resources/bootstrap.yaml
damongreen@Damons-MacBook-Pro-2 service-auth-provider-app % ./bin/check-all-vaults-for-s2s-secret nfdiv-cos 
INFO: Found secret nfdiv-cos in environment demo
INFO: Found secret nfdiv-cos in environment aat
INFO: Found secret nfdiv-cos in environment prod
INFO: Found secret nfdiv-cos in environment perftest
INFO: Found secret nfdiv-cos in environment ithc
damongreen@Damons-MacBook-Pro-2 service-auth-provider-app % ./bin/check-all-vaults-for-s2s-secret nfdiv-cms
INFO: Found secret nfdiv-cms in environment …
=> Add No Fault Divorce

build.gradle
=> Bump tomcat

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml, src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/RDCC-2141
```
m_794168@AMBGB000096 service-auth-provider-app % ./bin/set-secret-in-all-vaults rd-profile-sync
INFO: Found secret rd-profile-sync in environment demo
INFO: Found secret rd-profile-sync in environment aat
INFO: Found secret rd-profile-sync in environment prod
INFO: Found secret rd-profile-sync in environment perftest
INFO: Found secret rd-profile-sync in environment ithc
```
```
[ ] Yes
[X] No
```
=> Create secret for rd-profile-sync service

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml, src/main/resources/bootstrap.yaml
Adds camunda-bpm secret
```
❯ ./set-secret-in-all-vaults camunda-bpm                                                                                                                                                                                     09:51:53 
INFO: Found secret camunda-bpm in environment demo
INFO: Found secret camunda-bpm in environment aat
INFO: Found secret camunda-bpm in environment prod
INFO: Found secret camunda-bpm in environment perftest
INFO: Found secret camunda-bpm in environment ithc
```
```
[ ] Yes
[ ] No
```
=> Add camunda-bpm secret

Jenkinsfile_CNP, build.gradle, src/contractTest/java/uk/gov/hmcts/auth/provider/service/api/auth/AuthControllerProviderContext.java, src/contractTest/java/uk/gov/hmcts/auth/provider/service/api/auth/AuthControllerProviderTest.java, src/main/resources/application.yml
=> Ta 426 pact provider test

Jenkinsfile_CNP
=> TA-426: Fix pact branch name for master

README.md, charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml, src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/NFDIV-477
Adds nfdiv-case-api
```
➜  bin git:(master) ./set-secret-in-all-vaults nfdiv-case-api
INFO: Found secret nfdiv-case-api in environment demo
INFO: Found secret nfdiv-case-api in environment aat
INFO: Found secret nfdiv-case-api in environment prod
INFO: Found secret nfdiv-case-api in environment perftest
INFO: Found secret nfdiv-case-api in environment ithc
```
```
[ ] Yes
[ x] No
```
=> Added nfdiv case api s2s secret

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml, src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/AM-1205
Adding a new microservice
AMBGB000014:bin 736062$ ./check-all-vaults-for-s2s-secret am-role-assignment-refresh-batch
INFO: Found secret am-role-assignment-refresh-batch in environment demo
INFO: Found secret am-role-assignment-refresh-batch in environment aat
INFO: Found secret am-role-assignment-refresh-batch in environment prod
INFO: Found secret am-role-assignment-refresh-batch in environment perftest
INFO: Found secret am-role-assignment-refresh-batch in environment ithc
```
[ ] Yes
[x] No
```
=> am-role-assignment-refresh-batch

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml, src/main/resources/bootstrap.yaml
JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/EM-3454
Change description
Adding a new microservice
yogeshhullatti@Yogeshs-MacBook-Pro bin % ./check-all-vaults-for-s2s-secret em-hrs-api
INFO: Found secret em-hrs-api in environment demo
INFO: Found secret em-hrs-api in environment aat
INFO: Found secret em-hrs-api in environment prod
INFO: Found secret em-hrs-api in environment perftest
INFO: Found secret em-hrs-api in environment ithc
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[x] No
=> Added in key for em-hrs-api

build.gradle
=> TA-426: Fix jupiter dependabot class path issue

build.gradle, charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml, src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/EM-3455
Added in key for em-hrs-ingestor
yogeshhullatti@Yogeshs-MacBook-Pro service-auth-provider-app % ./bin/check-all-vaults-for-s2s-secret em-hrs-ingestor
INFO: Found secret em-hrs-ingestor in environment demo
INFO: Found secret em-hrs-ingestor in environment aat
INFO: Found secret em-hrs-ingestor in environment prod
INFO: Found secret em-hrs-ingestor in environment perftest
INFO: Found secret em-hrs-ingestor in environment ithc
```
[ ] Yes
[X] No
```
=> Added in key for em-hrs-ingestor

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml
https://tools.hmcts.net/jira/browse/CMC-1541
```
[ ] Yes
[x] No
```
=> Added civil_service

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml
JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/RWA-542
Change description
Add key for wa-task-monitor
=> add client service name

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml
https://tools.hmcts.net/jira/browse/CMC-1557
```
[ ] Yes
[x] No
```
=> Removed unspec_service after transition to civil_service

build.gradle, charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml, src/test/resources/application.yml
**ran `./bin/set-secret-in-all-vaults refunds-api`  got the below output **
INFO: Found secret refunds-api in environment demo
INFO: Found secret refunds-api in environment aat
INFO: Found secret refunds-api in environment prod
INFO: Found secret refunds-api in environment perftest
INFO: Found secret refunds-api in environment ithc
```
[ ] Yes
[ ] No
```
=> service auth for refunds api

charts/rpe-service-auth-provider/Chart.yaml, infrastructure/main.tf, infrastructure/state.tf
https://tools.hmcts.net/jira/browse/DTSPO-4621
move azuread to state.tf
```
[ ] Yes
[x] No
```
=> Move azuread to state.tf

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml
https://tools.hmcts.net/jira/browse/LAU-84
Adding S2S Key for lau-case-backend app.
Davids-MBP:bin davejones$ ./set-secret-in-all-vaults lau-case-backend
INFO: Found secret lau-case-backend in environment demo
INFO: Found secret lau-case-backend in environment aat
INFO: Found secret lau-case-backend in environment prod
INFO: Found secret lau-case-backend in environment perftest
INFO: Found secret lau-case-backend in environment ithc
```
[ ] Yes
[x] No
```
=> LAU-84: Adding S2S Key for lau-case-backend app.

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml
I have ran the above command  ./bin/set-secret-in-all-vaults ccpay-cpo-function-node, I got the below response
INFO: Found secret ccpay-cpo-function-node in environment demo
INFO: Found secret ccpay-cpo-function-node in environment aat
INFO: Found secret ccpay-cpo-function-node in environment prod
INFO: Found secret ccpay-cpo-function-node in environment perftest
INFO: Found secret ccpay-cpo-function-node in environment ithc
```
[ ] Yes …
```
=> ccpay-cpo-fuction-node

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml
https://tools.hmcts.net/jira/browse/LAU-84
Adding S2S Key for lau-case-frontend app.
Davids-MacBook-Pro:bin davejones$ ./set-secret-in-all-vaults lau-case-frontend
INFO: Found secret lau-case-frontend in environment demo
INFO: Found secret lau-case-frontend in environment aat
INFO: Found secret lau-case-frontend in environment prod
INFO: Found secret lau-case-frontend in environment perftest
INFO: Found secret lau-case-frontend in environment ithc
```
[ ] Yes
[x] No
```
=> LAU-84: Adding S2S Key for lau-case-frontend app

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml
added adoption s2s secret
```
m_2062795@AMBGB000406 service-auth-provider-app % ./bin/set-secret-in-all-vaults adoption-web
INFO: Found secret adoption-web in environment demo
INFO: Found secret adoption-web in environment aat
INFO: Found secret adoption-web in environment prod
INFO: Found secret adoption-web in environment perftest
INFO: Found secret adoption-web in environment ithc
```
=> added adoption s2s secret

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml
https://tools.hmcts.net/jira/browse/LAU-169
Adding S2S Key for lau-idam-frontend app.
Davids-MacBook-Pro:bin davejones$ ./set-secret-in-all-vaults lau-idam-frontend
INFO: Found secret lau-idam-frontend in environment demo
INFO: Found secret lau-idam-frontend in environment aat
INFO: Found secret lau-idam-frontend in environment prod
INFO: Found secret lau-idam-frontend in environment perftest
INFO: Found secret lau-idam-frontend in environment ithc
```
[ ] Yes
[x] No
```
=> LAU-169: Update to add lau-idam-frontend.

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml
https://tools.hmcts.net/jira/browse/PRL-545
Registering Domestic abuse backend API (da-cos-api) with S2S service.
- Wasn't aware this needs to be added. I have checked all the S2S vaults (S2S-aat, S2S-Demo etc ) and the secret is there.
```
[ ] Yes
[x] No
```
=> Register DA with S2S Service

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml
https://tools.hmcts.net/jira/browse/RET-84
Add et-ccd-callbacks service
jamesturnbull@L1063 service-auth-provider-app % ./bin/check-all-vaults-for-s2s-secret et-ccd-callbacks
INFO: Found secret et-ccd-callbacks in environment demo
INFO: Found secret et-ccd-callbacks in environment aat
INFO: Found secret et-ccd-callbacks in environment prod
INFO: Found secret et-ccd-callbacks in environment perftest
INFO: Found secret et-ccd-callbacks in environment ithc
```
[ ] Yes
[x] No
```
=> Add et-ccd-callbacks

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml
https://tools.hmcts.net/jira/browse/RET-84
Update Employment Tribunal services
jamesturnbull@L1063 service-auth-provider-app % ./bin/set-secret-in-all-vaults et-cos
INFO: Found secret et-cos in environment demo
INFO: Found secret et-cos in environment aat
INFO: Found secret et-cos in environment prod
INFO: Found secret et-cos in environment perftest
INFO: Found secret et-cos in environment ithc
jamesturnbull@L1063 service-auth-provider-app % ./bin/set-secret-in-all-vaults et-msg-handler
INFO: Found secret et-msg-handler in environment demo
INFO: Found secret et-msg-handler in environment aat
INFO: Found secret et-msg-handler in environment prod
INFO: Found secret et-msg-handler in environment perftest
INFO: Found secret et-msg-handler in environment ithc
**Does this PR introduce a …
=> Update Employment Tribunal services

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml
Add lau-frontend microservice secret.
% ./bin/check-all-vaults-for-s2s-secret lau-frontend
INFO: Found secret lau-frontend in environment demo
INFO: Found secret lau-frontend in environment aat
INFO: Found secret lau-frontend in environment prod
INFO: Found secret lau-frontend in environment perftest
INFO: Found secret lau-frontend in environment ithc
```
[ ] Yes
[x] No
```
=> Update to add lau-frontend microservice

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml
INFO: Found secret notifications-service in environment demo
INFO: Found secret notifications-service in environment aat
INFO: Found secret notifications-service in environment prod
INFO: Found secret notifications-service in environment perftest
INFO: Found secret notifications-service in environment ithc
```
[ ] Yes
[ ] No
```
=> notification s2s

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml
It has been agreed technically that Domestic Abuse and Child arrangement under PrivateLaw project will use the same codebase. Therefore DA specific configuration is no longer required.
```
[ ] Yes
[x] No
```
=> Off board Domestic Abuse changes

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml
https://tools.hmcts.net/jira/browse/LAU-268
Remove Lau Case and Lau Idam frontend applications. These have been replaced with a single application Lau-Frontend.
```
[ ] Yes
[x] No
```
=> LAU-268 Remove lau-case and lau-idam frontend

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml
https://tools.hmcts.net/jira/browse/SSCS-10053
./bin/set-secret-in-all-vaults sscs-hearings-api
INFO: Found secret sscs-hearings-api in environment demo
INFO: Found secret sscs-hearings-api in environment aat
ERROR: Didn't find secret sscs-hearings-api in environment prod
INFO: Found secret sscs-hearings-api in environment perftest
INFO: Found secret sscs-hearings-api in environment ithc
```
[ ] Yes
[X ] No
```
=> sscs-10053-Setup sscs-hearings-api

infrastructure/main.tf
It's being stored twice
Will re-add in a follow up
=> Remove connection string

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml
=> add service for s2s authentication

Dockerfile, acb.tpl.yaml
https://tools.hmcts.net/jira/browse/DTSPO-5984
Added multi-architecture ACR Task template.
```
[ ] Yes
[X] No
```
=> Added multi-architecture ACR Task template.

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml
Add the HMC CFT Hearing Service
```
INFO: Found secret hmc-cft-hearing-service in environment demo
INFO: Found secret hmc-cft-hearing-service in environment aat
INFO: Found secret hmc-cft-hearing-service in environment prod
INFO: Found secret hmc-cft-hearing-service in environment perftest
INFO: Found secret hmc-cft-hearing-service in environment ithc
```
```
[ ] Yes
[x] No
```
=> Add HMC CFT Hearing Service for S2S

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml
Prod doesn't exist yet
INFO: Found secret et-sya-api in environment demo
INFO: Found secret et-sya-api in environment aat
ERROR: Didn't find secret et-sya-api in environment prod
INFO: Found secret et-sya-api in environment perftest
JIRA Link
https://tools.hmcts.net/jira/browse/RET-913
```
[ ] Yes
[ x] No
```
=> Adding et_sya_api service

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml
Adding new service 'family-bulk-scan-api' for s2s authentication
Output:
m_525526@AMBGB000477 bin % ./set-secret-in-all-vaults family-bulk-scan-api
INFO: Found secret family-bulk-scan-api in environment demo
INFO: Found secret family-bulk-scan-api in environment aat
INFO: Found secret family-bulk-scan-api in environment prod
INFO: Found secret family-bulk-scan-api in environment perftest
INFO: Found secret family-bulk-scan-api in environment ithc
```
[ ] Yes
[x ] No
```
=> Cshiwarale patch 1

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml, dependency-check-suppressions.xml
Add HMI Inbound Adapter
```
INFO: Found secret hmc-hmi-inbound-adapter in environment demo
INFO: Found secret hmc-hmi-inbound-adapter in environment aat
INFO: Found secret hmc-hmi-inbound-adapter in environment prod
INFO: Found secret hmc-hmi-inbound-adapter in environment perftest
INFO: Found secret hmc-hmi-inbound-adapter in environment ithc
```
```
[ ] Yes
[x] No
```
=> Add HMC HMI Inbound Adapter

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml
S2S Onboarding for new component fis-cos-api
m_525526@AMBGB000477 service-auth-provider-app % ./bin/set-secret-in-all-vaults fis-cos-api
INFO: Found secret fis-cos-api in environment demo
INFO: Found secret fis-cos-api in environment aat
INFO: Found secret fis-cos-api in environment prod
INFO: Found secret fis-cos-api in environment perftest
INFO: Found secret fis-cos-api in environment ithc
```
[ ] Yes
[ X] No
```
=> S2S Onboarding for new component fis-cos-api

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml
https://tools.hmcts.net/jira/browse/LAU-329
Added new client service (ccd-case-disposer) to service auth provider
INFO: Found secret ccd-case-disposer in environment demo
INFO: Found secret ccd-case-disposer in environment aat
INFO: Found secret ccd-case-disposer in environment prod
INFO: Found secret ccd-case-disposer in environment perftest
INFO: Found secret ccd-case-disposer in environment ithc
[ ] Yes
[X] No
=> LAU-329 - Invoke documents delete from case disposer

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml, dependency-check-suppressions.xml
Add the Translation Service
If you're adding a new secret then do the following
Run the script in ./bin/set-secret-in-all-vaults <microservice-name> and paste the output below
```
INFO: Found secret ts-translation-service in environment demo
INFO: Found secret ts-translation-service in environment aat
INFO: Found secret ts-translation-service in environment prod
INFO: Found secret ts-translation-service in environment perftest
INFO: Found secret ts-translation-service in environment ithc
```
```
[ ] Yes
[ X] No
```
=> WLTS-14 Add Translation Service for S2S

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/DTSPO-8829
Master build is broken due to 4 CVE errors. Fixed 3 of them with spring-boot and tomcat version upgrade. 1 CVE seems to be not-fixable at the moment. Updated the dependency suppression file with the details.
```
[ ] Yes
[x] No
```
=> CVE fix and suppression to unblock the pipeline

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml, dependency-check-suppressions.xml
Add the ccd-next-hearing-date-updater 
```
INFO: Found secret ccd-next-hearing-date-updater in environment demo
INFO: Found secret ccd-next-hearing-date-updater in environment aat
INFO: Found secret ccd-next-hearing-date-updater in environment prod
INFO: Found secret ccd-next-hearing-date-updater in environment perftest
INFO: Found secret ccd-next-hearing-date-updater in environment ithc
```
```
[ ] Yes
[x] No
```
=>   HMAN-366: S2S configuration on higher environments

build.gradle, dependency-check-suppressions.xml
=> Some dependency updates

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/ST-795
```
[ ] Yes
[ x] No
```
=> ST-795-sptribs-case-api microservice has been added

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml
AMBGB000242:service-auth-provider-app m_123502$ ./bin/set-secret-in-all-vaults fis-hmc-api
INFO: Found secret fis-hmc-api in environment demo
INFO: Found secret fis-hmc-api in environment aat
INFO: Found secret fis-hmc-api in environment prod
INFO: Found secret fis-hmc-api in environment perftest
INFO: Found secret fis-hmc-api in environment ithc
AMBGB000242:service-auth-provider-app m_123502$ 
```
[ ] Yes
[ ] No
```
=> fis-hmc-api s2s creation

charts/rpe-service-auth-provider/values.yaml
https://tools.hmcts.net/jira/browse/ST-872
Adding sptribs DSS backend microservice
```
[ ] Yes
[x] No
```
=> Adding DSS backend microservice

charts/rpe-service-auth-provider/Chart.yaml
https://tools.hmcts.net/jira/browse/ST-872
Forgot to bump minor version when adding new microservice.
```
[ ] Yes
[ ] No
```
=> St 872 bump helm chart version

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml, dependency-check-suppressions.xml
Adding new general application service
```
[ ] Yes
[ ] No
```
=> adding general application since its a new service

.github/renovate.json, Dockerfile, dependency-check-suppressions.xml
=> Add renovate for appinsights upgrade

.github/renovate.json
=> Enable regex managers

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml
https://tools.hmcts.net/jira/browse/ST-1125
Add sptribs-frontend service
INFO: Found secret sptribs-frontend in environment demo
INFO: Found secret sptribs-frontend in environment aat
INFO: Found secret sptribs-frontend in environment prod
INFO: Found secret sptribs-frontend in environment perftest
INFO: Found secret sptribs-frontend in environment ithc
```
[ ] Yes
[x] No
```
=> ST-1125 Add sptribs-frontend service

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml
https://tools.hmcts.net/jira/browse/IJPS-51
add jps-judicial-payment-service and jps-judicial-payment-frontend
```
rebeccabaker@MBP-C02FXECCMD6M service-auth-provider-app % ./bin/check-all-vaults-for-s2s-secret jps-judicial-payment-service
INFO: Found secret jps-judicial-payment-service in environment demo
INFO: Found secret jps-judicial-payment-service in environment aat
INFO: Found secret jps-judicial-payment-service in environment prod
INFO: Found secret jps-judicial-payment-service in environment perftest
INFO: Found secret jps-judicial-payment-service in environment ithc
rebeccabaker@MBP-C02FXECCMD6M service-auth-provider-app % ./bin/check-all-vaults-for-s2s-secret jps-judicial-payment-frontend
INFO: Found secret jps-judicial-payment-frontend in environment demo
INFO: Found secret …
```
=> IJPS-51 add JPS Services

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml
https://tools.hmcts.net/jira/browse/CUIRA-88
Add cui-ra to the helm charts
INFO: Found secret cui-ra in environment demo
INFO: Found secret cui-ra in environment aat
INFO: Found secret cui-ra in environment prod
INFO: Found secret cui-ra in environment perftest
INFO: Found secret cui-ra in environment ithc
```
[ ] Yes
[X] No
```
=> Added cui-ra to charts

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml
https://tools.hmcts.net/jira/browse/SDT-43
./bin/set-secret-in-all-vaults civil-sdt
INFO: Found secret civil-sdt in environment demo
INFO: Found secret civil-sdt in environment aat
INFO: Found secret civil-sdt in environment prod
INFO: Found secret civil-sdt in environment perftest
INFO: Found secret civil-sdt in environment ithc
```
[ ] Yes
[X ] No
```
=> SDT-43: create s2s secrect for Civil SDT

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml
Add new idam-user-disposer service
https://tools.hmcts.net/jira/browse/LAU-625
```
[ ] Yes
[x] No
```
=> Add new idam-user-disposer service

Jenkinsfile_CNP, build.gradle
=> Remove unnecessary override of groovy

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml
adding cui microserviceKey
```
[ ] Yes
[ ] No
```
=> adding cui microserviceKey

build.gradle, dependency-check-suppressions.xml
Reverts hmcts/service-auth-provider-app#779
Pipeline currently failing
Error is UnknownClass.JUnit Jupiter > UnknownClass.initializationError FAILED
Reverting to help confirm this was the issue
=> Revert "Update junit5 monorepo"

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml
https://tools.hmcts.net/jira/browse/RET-3993
Add the et-hearings-api service
INFO: Found secret et-hearings-api in environment demo
INFO: Found secret et-hearings-api in environment aat
INFO: Found secret et-hearings-api in environment prod
INFO: Found secret et-hearings-api in environment perftest
INFO: Found secret et-hearings-api in environment ithc
```
[ ] Yes
[x] No
```
=> Add et-hearings-api service

build.gradle, dependency-check-suppressions.xml
Resolves CVE-2023-41080
```
[ ] Yes
[ ] No
```
=> Upgrade tomcat

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml
https://tools.hmcts.net/jira/browse/SIDM-8836
Add the idam-user-profile-bridge service
INFO: Found secret idam-user-profile-bridge in environment demo
INFO: Found secret idam-user-profile-bridge in environment aat
INFO: Found secret idam-user-profile-bridge in environment prod
INFO: Found secret idam-user-profile-bridge in environment perftest
INFO: Found secret idam-user-profile-bridge in environment ithc
```
[ ] Yes
[X] No
```
=> Add new idam-user-profile-bridge service

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml
https://tools.hmcts.net/jira/browse/LAU-710
Changing the service name from Idam-user-disposer to disposer-idam-user
```
[ ] Yes
[x] No
```
=> Update disposer-idam-user in values.yaml

build.gradle
DTSPO-15411
DTSPO-15411 - build fix for Workload Identity update
```
[ ] Yes
[ x] No
```
=> DTSPO-15411 - build fix for Workload Identity update

build.gradle
Dependency fix check for Tomcat CVE-2023-42795 & CVE-2023-45648
```
[ ] Yes
[ ] No
```
=> Dependency fix check for Tomcat CVE-2023-42795 & CVE-2023-45648

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml
https://tools.hmcts.net/jira/browse/DTSSTCI-377
Set up sptribs-dss-update-case-web microservice s2s token
```
[ ] Yes
[x] No
```
=> Set up sptribs-dss-update-case-web microservice s2s token

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml
Correct microservice name for Sptribs DSS Update Case to use snake case instead of kebab as used in all other config
=> Correct microservice name for Sptribs DSS Update Case 

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml
https://tools.hmcts.net/jira/browse/DTSSTCI-866
Remove st-cron-trigger config
```
[ ] Yes
[ ] No
```
=> Remove st-cron-trigger config

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml
https://tools.hmcts.net/jira/browse/IJPS-142
decommissioning JPS
```
[ ] Yes
[ ] No
```
=> decommissioning JPS

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml
```
Cubeloid:service-auth-provider-app praveen$ ./bin/set-secret-in-all-vaults pcs-api
INFO: Found secret pcs-api in environment sandbox
INFO: Found secret pcs-api in environment demo
INFO: Found secret pcs-api in environment aat
INFO: Found secret pcs-api in environment prod
INFO: Found secret pcs-api in environment perftest
INFO: Found secret pcs-api in environment ithc
Cubeloid:service-auth-provider-app praveen$ ./bin/set-secret-in-all-vaults pcs-frontend
INFO: Found secret pcs-frontend in environment sandbox
INFO: Found secret pcs-frontend in environment demo
INFO: Found secret pcs-frontend in environment aat
INFO: Found secret pcs-frontend in environment prod
INFO: Found secret pcs-frontend in environment perftest
INFO: Found secret pcs-frontend in environment ithc
```
**Does this PR …
=> Add pcs apps to s2s

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml
CRF-12 (https://tools.hmcts.net/jira/browse/CRF-12)
Add civil-rtl-export service to s2s
Secrets were manually added to s2s key vaults.
Output from `./bin/check-all-vaults-for-s2s-secret civil-rtl-export`:
```
INFO: Found secret civil-rtl-export in environment sandbox
INFO: Found secret civil-rtl-export in environment demo
INFO: Found secret civil-rtl-export in environment aat
INFO: Found secret civil-rtl-export in environment prod
INFO: Found secret civil-rtl-export in environment perftest
INFO: Found secret civil-rtl-export in environment ithc
```
```
[ ] Yes
[x] No
```
=> Add civil-rtl-export service

charts/rpe-service-auth-provider/Chart.yaml, charts/rpe-service-auth-provider/values.yaml
https://tools.hmcts.net/jira/browse/LAU-1105
Add disposer-fee-and-pay microservice
➜  service-auth-provider-app git:(master) ✗ ./bin/set-secret-in-all-vaults disposer-fee-and-pay
INFO: Found secret disposer-fee-and-pay in environment sandbox
INFO: Found secret disposer-fee-and-pay in environment demo
INFO: Found secret disposer-fee-and-pay in environment aat
INFO: Found secret disposer-fee-and-pay in environment prod
INFO: Found secret disposer-fee-and-pay in environment perftest
INFO: Found secret disposer-fee-and-pay in environment ithc
```
[ ] Yes
[x] No
```
=> LAU-1105 add disposer-fee-and-pay service

build.gradle
https://tools.hmcts.net/jira/browse/DTSPO-25049
Reverted recent Junit update as causing pipeline failure
```
[ ] Yes
[X] No
```
=> Revert-JUnit-Update

charts/rpe-service-auth-provider/Chart.yaml
DTSPB-4796
bump chart version to rotate secrets
```
[ ] Yes
[x] No
```
=> DTSPB-4796 bump chart version

charts/rpe-service-auth-provider/Chart.yaml
https://tools.hmcts.net/jira/browse/PAY-7847
Update Paybubble S2S secret.
```
[ ] Yes
[x] No
```
=> PAY-7847: Update S2S secret for paybubble

charts/rpe-service-auth-provider/Chart.yaml
https://tools.hmcts.net/jira/browse/DTSRD-4664
```
[ ] Yes
[x] No
```
=> Update Chart.yaml to new version
