- api/src/main/java/uk/gov/hmcts/auth/provider/service/api/auth/RootController.java
- api/src/test/java/uk/gov/hmcts/auth/provider/service/api/componenttests/RootEndpointComponentTest.java
- api/src/test/java/uk/gov/hmcts/auth/provider/service/api/componenttests/dsl/ServiceAuthProviderTestDsl.java
Azure App Service has "Always On" feature which silently hits "/" root endpoint. Adding welcome message to fix 404 reporting in AppInsights
```
[ ] Yes
[x] No
```
> Introduce RootController

- infrastructure/main.tf
Missing entry in the key vault blocks certain environments.
To be restored later.
This reverts commit 1abc9773cdd2a3e82eb1610bcb08c21c67e910f9.
```
[ ] Yes
[x] No
```
> Revert "Add FinRem - DraftStore micro service to s2s auth (#51)"

- infrastructure/main.tf
Added micro service keys for Financial Remedy frontend (finRem) and finRemDraftStore
https://tools.hmcts.net/jira/browse/FR-167
Added micro service keys for Financial Remedy frontend (finRem) and finRemDraftStore
```
[ ] Yes
[ x] No
```
> Added micro service keys for Financial Remedy frontend (finRem) and finRemDraftStore

- infrastructure/main.tf
Add draft_store_tests to the list of recognised microservices. Smoke and functional tests for draft-store authenticate themselves as draft_store_tests when testing draft-store.
```
[ ] Yes
[x] No
```
> Add draft_store_tests to the list of recognised microservices

- infrastructure/main.tf
- Bulk scanning component needs to call Document management service which need s2s token.
- Keys added to Hashicorp Vault for test, preprod and prod paths.
```
[ ] Yes
[x ] No
```
> Add bulk scan key to s2s

- README.md
N/A
Fix doc for microservices configuration: `MICROSERVICE_KEYS_` instead of `MICROSERVICEKEYS_`
```
[ ] Yes
[x] No
```
> Fix README typo for service config

- src/main/java/uk/gov/hmcts/auth/provider/service/api/model/SignIn.java
both java client:
https://github.com/hmcts/service-auth-provider-java-client/blob/master/src/main/java/uk/gov/hmcts/reform/authorisation/generators/ServiceAuthTokenGenerator.java#L36
and nodejs client:
https://github.com/hmcts/ccd-api-gateway/blob/master/app/service/service-token-generator.js#L23
send `oneTimePassword` in JSON
> Accept old sign-in payload

- infrastructure/main.tf
- infrastructure/output.tf
Preview S2S uses AAT vault, but its terraform code also tries to create it. This pull request prevents that from happening. It still creates a preview (not aat) vault, as you can't set count to 0, but doesn't use it.
```
[ ] Yes
[x] No
```
> [PREVIEW] Prevent attempts to create aat vault in preview builds

- Jenkinsfile_CNP
- Jenkinsfile_parameterized
- infrastructure/main.tf
- infrastructure/output.tf
- infrastructure/preview.tfvars
https://tools.hmcts.net/jira/browse/RPE-614
Retrieve microservice secrets from Azure Key Vault and put them in application settings.
To come after this pull request:
- getting rid of Hashicorp Vault and the application settings that come from its secrets
- making the application use the new settings
```
[ ] Yes
[x] No
```
> [PREVIEW] Retrieve microservice secrets from Azure Key Vault

- infrastructure/main.tf
Note that this new secret is read from the azure vault, not tactical hashicorp vault.
Added secrets in saat, aat and prod.
> [PREVIEW] Add config for bulk-scan-orchestrator service

- README.md
- infrastructure/main.tf
Don't merge before Monday, as this change affects all services
https://tools.hmcts.net/jira/browse/RPE-544
Make Terraform create application settings based on secrets stored in Azure Vault. Currently it uses secrets from Tactical (Hashicorp) Vault.
Old (hashicorp vault) secrets are still retrieved, but are no longer kept in application settings. They will be removed in a future PR.
```
[ ] Yes
[x] No
```
> [PREVIEW] Use secrets from Azure Vault

- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RPE-614
Remove (Hashicorp) vault provider config from infrastructure code. We're not using Hashicorp vault anymore.
```
[ ] Yes
[x] No
```
> [PREVIEW] Remove (Hashicorp) vault provider config

- src/main/java/uk/gov/hmcts/auth/provider/service/api/ResponseExceptionHandler.java
- src/test/java/uk/gov/hmcts/auth/provider/service/api/componenttests/DetailsComponentTest.java
- src/test/java/uk/gov/hmcts/auth/provider/service/api/componenttests/LeaseComponentTest.java
Some endpoints return plain text response, while errors are always json objects.
In case client requires `text/plain` (some do: [link](https://github.com/hmcts/service-auth-provider-java-client/blob/master/src/main/java/uk/gov/hmcts/reform/authorisation/ServiceAuthorisationApi.java#L28)) return just the error string.
> Content negotiation in error handler

- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/CET-422
Add S2S key name for cet-frontend
corresponding keys have been added to the various environments as per instructions on the ReadMe file.
```
ERROR: Didn't find secret …
```
> Add S2S key name for cet-frontend

- infrastructure/main.tf
Hit the azurerm issue trying to deploy this app to saat.
```
[ ] Yes
[x] No
```
> Lock Terraform azurerm provider to 1.19.0

- build.gradle
- src/main/java/uk/gov/hmcts/auth/provider/service/api/auth/exceptions/InvalidAuthHeaderException.java
- src/main/java/uk/gov/hmcts/auth/provider/service/api/auth/exceptions/InvalidOneTimePasswordException.java
- src/main/java/uk/gov/hmcts/auth/provider/service/api/auth/exceptions/TokenExpiredException.java
- src/main/java/uk/gov/hmcts/auth/provider/service/api/auth/exceptions/TokenSignatureException.java
- src/main/java/uk/gov/hmcts/auth/provider/service/api/auth/exceptions/UnmappedTokenException.java
- src/main/java/uk/gov/hmcts/auth/provider/service/api/microservice/UnknownMicroserviceException.java
The new logging has deprecated the exceptions that were used for alerting which are now not used.
> moving to logging library 4.0.0

- infrastructure/main.tf
Adding s2s token for IAC.
```
ERROR: Didn't find secret iac in environment sandbox
ERROR: Didn't find secret iac in environment saat
INFO: Found secret iac in environment sprod
INFO: Found secret iac in environment demo
ERROR: Didn't find secret iac in environment hmctsdemo
INFO: Found secret iac in environment aat
INFO: Found secret iac in environment …
```
> Added IAC s2s key

- infrastructure/main.tf
N/A
Added document assembly and template management API microservice keys
Template Management API:
INFO: Found secret dg-template-management-api in environment sandbox
INFO: Found secret dg-template-management-api in environment saat
INFO: Found secret dg-template-management-api in environment sprod
INFO: Found secret dg-template-management-api in environment demo
INFO: Found secret dg-template-management-api in environment hmctsdemo
INFO: Found secret dg-template-management-api in environment aat
INFO: Found secret dg-template-management-api in environment prod
Document Assembly API
INFO: Found secret dg-docassembly-api in environment sandbox
INFO: Found secret dg-docassembly-api in environment saat
INFO: Found secret dg-docassembly-api in environment sprod
INFO: Found secret …
> add doc assembly api and template management api keys

- charts/rpe-service-auth-provider/values.yaml
- infrastructure/main.tf
- src/main/resources/bootstrap.yaml
Add the following reference data api services:
- rd-professional-api
- rd-user-profile-api
Outputs of bin/check-all-vaults-for-s2s-secret
```
INFO: Found secret rd-professional-api in environment sandbox
INFO: Found secret rd-professional-api in environment saat
INFO: Found secret rd-professional-api in environment sprod
INFO: Found secret rd-professional-api in environment demo
INFO: Found secret rd-professional-api in environment hmctsdemo
INFO: Found secret rd-professional-api in environment aat
INFO: Found secret rd-professional-api in environment prod
```
```
INFO: Found secret rd-user-profile-api in environment sandbox
INFO: Found secret rd-user-profile-api in environment saat
INFO: Found secret rd-user-profile-api in environment sprod
INFO: Found secret rd-user-profile-api in …
```
> Add reference data api services

- CODEOWNERS
Add CODEOWNERS so that we can allow dependabot to merge it's changes and not restrict to a specific team merging (only restrict on review)
https://github.com/hmcts/service-auth-provider-app/pull/157#issuecomment-513666111
```
[ ] Yes
[ ] No
```
> Add CODEOWNERS (platform engineering)

- build.gradle
N/A
Bumps tomcat to use 9.039
```
[ ] Yes
[ x] No
```
> CVE-2020-13943: Bump tomcat to 9.0.39

- charts/rpe-service-auth-provider/Chart.yaml
- charts/rpe-service-auth-provider/values.yaml
Fix error in microservice key alias for ET
```
[ ] Yes
[x] No
```
> Fix alias for et keys

- charts/rpe-service-auth-provider/Chart.yaml
- charts/rpe-service-auth-provider/values.yaml
https://tools.hmcts.net/jira/browse/LAU-172
Updating the service-auth-provider to support s2s idam-api key.
service-auth-provider-app davejones$ ./bin/set-secret-in-all-vaults idam-api
INFO: Found secret idam-api in environment demo
INFO: Found secret idam-api in environment aat
INFO: Found secret idam-api in environment prod
INFO: Found secret idam-api in environment perftest
INFO: Found secret idam-api in environment ithc
```
[ ] Yes
[x] No
```
> LAU-172: Adding IdAM-API key.

- build.gradle
Pipeline broken since https://github.com/hmcts/service-auth-provider-app/pull/673 for Pact
Reverting to make sure that was the issue and then can find the fix
```
[ ] Yes
[x ] No
```
> revert - pipeline broken since PR 673, pact upgrade

- bin/set-secret-in-all-vaults
The set secret script was setting keyvault values with b'secret'. using .decode() removed this issue. 
```
[ ] Yes
[X] No
```
> decode output from python

- Jenkinsfile_CNP
- src/contractTest/java/uk/gov/hmcts/auth/provider/service/api/auth/AuthControllerProviderTest.java
XUI broke the pact tests in https://github.com/hmcts/rpx-xui-approve-org/pull/798 and https://github.com/hmcts/rpx-xui-webapp/pull/3362
They specified the wrong content type response and changed the state name from a valid one to one that didn't exist.
Failures:
* `Pact between xui_approveorg (b202ce9) and s2s_auth - The url, the password and microservice`
* `Pact between xui_webApp (e5f42ea) and s2s_auth - The url, the password and microservice`
Also a PRL one was failing:
* `Pact between prl_cos_api (6127edc6b) and s2s_auth - a request for a token`
not looked at the prl one.
> Fix pact tests

- infrastructure/main.tf
Jira link (if applicable)
https://tools.hmcts.net/jira/browse/DTSPO-15909
Change description
Updating azurerm_application_insights resource and replacing it with module terraform-module-application-insights
This will allow us to migrate Classic Application Insights using https://github.com/hmcts/app-insights-migration-tool as Classic Application Insights will deprecated and will be retired in February 2024.
> DTSPO-15909 - updating app insights to module

- bin/check-all-vaults-for-s2s-secret
- bin/set-secret-in-all-vaults
Reverts hmcts/service-auth-provider-app#252
A new secret was created for [st-cron](https://github.com/hmcts/service-auth-provider-app/pull/950) which is causing sandbox pods to fail because it doesn't exist in the sandbox vault which has been recreated since this original PR was merged
> Revert "Remove sandbox from script"

- build.gradle
Reverts hmcts/service-auth-provider-app#1046
**Description** 
- This PR reverts the recent update of `JUnit 5.12.0` and `junit-platform-commons 1.12.0` back to `JUnit 5.11.4` and `junit-platform-commons 1.11.4`. The upgrade caused test discovery failures due to incompatibility between `JUnit 5.12.0` and the JUnit Platform version used.
**Issue**
- The project was updated to `JUnit 5.12.0` but continued using `junit-platform-commons 1.12.0`.
- This mismatch caused a `NoSuchMethodError` during test discovery because `junit-jupiter-engine 5.12.0` expects a `method (getOutputDirectoryProvider())` that does not exist in `junit-platform-commons 1.12.0`.
- As a result, tests failed to execute with errors in `JUnitPlatformTestClassProcessor`.
**Changes Reverted**
- **JUnit Jupiter** downgraded …
> Revert "Update junit5 monorepo"

- .github/renovate.json
- build.gradle
- charts/rpe-service-auth-provider/Chart.yaml
- charts/rpe-service-auth-provider/values.yaml
https://tools.hmcts.net/jira/browse/PAY-7869
I've put a block on renovate updating the jupiter libraries for now as this is breaking the pact testing.
The change is to support Fee and Payments components using it's own s2s secret for the API Gateway instead of the shared secret 'api-gw'.
Only relevant s2s environments being shown.
./check-all-vaults-for-s2s-secret ccpay-gw
INFO: Found secret ccpay-gw in environment sandbox
INFO: Found secret ccpay-gw in environment prod
INFO: Found secret ccpay-gw in environment demo
INFO: Found secret ccpay-gw in environment aat
INFO: Found secret ccpay-gw in environment perftest
INFO: Found …
> PAY-7869: Adding new CCPAY API Gateway S2S Secret
